# frozen_string_literal: true

task default: :test

require "megatest/test_task"
Megatest::TestTask.create do |t|
  t.full_backtrace = true
  t.command = "bin/test"
end

namespace :test do
  task isolated: :railties do
    Dir.glob("#{__dir__}/test/**/*_test.rb").all? do |file|
      sh("bundle", "exec", "megatest", "-I#{__dir__}/lib", file)
    end || raise("Failures")
  end

  task :railties do
    ["active_model/railtie"].all? do |railtie|
      sh(Gem.ruby, "-r", railtie, "-e", "'OK'")
    end || raise("Failures")
  end
end
